apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: atlas
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-username/your-repo-name-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # You can add more environment variables or use a ConfigMap/Secret
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: backend-config
        #       key: db_host
      imagePullSecrets:
      - name: ghcr-secret 