apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas

resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ingress.yaml
  - config.yaml
  - secrets.yaml

# Uncomment and update if you want to add image tags
# images:
# - name: ghcr.io/your-username/your-repo-name-frontend
#   newTag: latest
# - name: ghcr.io/your-username/your-repo-name-backend
#   newTag: latest

# Uncomment if you want to add patches
# patches:
# - path: patches/increase-replicas.yaml
#   target:
#     kind: Deployment
#     name: frontend 