apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: atlas
type: Opaque
data:
  # These are base64 encoded values - use 'echo -n "your-secret" | base64' to encode
  # Example: DATABASE_PASSWORD: cGFzc3dvcmQ=
  # Replace these with your actual encoded secrets
  # DB_PASSWORD: ""
  # API_KEY: ""
  # JWT_SECRET: ""
  # Add any other sensitive data your application needs
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  CLICKHOUSE_USER: ZGVmYXVsdA==  # default
  CLICKHOUSE_PASSWORD: ""  # empty password 